export const ERROR_CODES = {
  // AUTH
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",

  // VALIDATION
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // USER
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",

  // GENERAL
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
};